name: Build APK

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      # Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Đổi tên file APK thành doki-<6 ký tự ngẫu nhiên>.apk
      - name: Rename APK
        run: |
          cd app/build/outputs/apk/debug
          NEW_NAME="doki-$(head /dev/urandom | tr -dc a-z0-9 | head -c 6).apk"
          mv app-debug.apk "$NEW_NAME"
          echo "APK_NAME=$NEW_NAME" >> $GITHUB_ENV

      # Xóa release & tag 'latest' cũ (nếu có)
      - name: Delete old release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release delete latest -y || true
          git push origin :refs/tags/latest || true

      # Tạo release mới & upload file APK
      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          files: app/build/outputs/apk/debug/${{ env.APK_NAME }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
